# 7timer astro weather helper

Simple helper `fetch_astro_weather_7timer` calls the open 7timer API and returns the JSON payload.

In [36]:
import pandas as pd
import json
import urllib.parse
import urllib.request

SEVEN_TIMER_API_URL = "https://www.7timer.info/bin/api.pl"


def fetch_astro_weather_7timer(longitude: float, latitude: float, product: str = "astro", output: str = "json") -> dict:
    """
    Get astronomy-oriented weather from 7timer and return the JSON response.
    Example endpoint: https://www.7timer.info/bin/api.pl?lon=2.32&lat=48.859&product=astro&output=json
    """
    params = urllib.parse.urlencode({"lon": longitude, "lat": latitude, "product": product, "output": output})
    url = f"{SEVEN_TIMER_API_URL}?{params}"
    try:
        with urllib.request.urlopen(url, timeout=10) as response:
            return json.load(response)
    except Exception as exc:  # noqa: BLE001
        return {"error": f"7timer request failed: {exc}", "url": url}

# Example usage (commented):
# result = fetch_astro_weather_7timer(longitude=2.32, latitude=48.859)
# result

In [41]:
request = fetch_astro_weather_7timer(2.34839, 48.85349)

In [42]:
request

{'product': 'astro',
 'init': '2025112906',
 'dataseries': [{'timepoint': 3,
   'cloudcover': 9,
   'seeing': 4,
   'transparency': 8,
   'lifted_index': 6,
   'rh2m': 15,
   'wind10m': {'direction': 'S', 'speed': 3},
   'temp2m': 8,
   'prec_type': 'none'},
  {'timepoint': 6,
   'cloudcover': 9,
   'seeing': 4,
   'transparency': 8,
   'lifted_index': 6,
   'rh2m': 13,
   'wind10m': {'direction': 'S', 'speed': 3},
   'temp2m': 9,
   'prec_type': 'none'},
  {'timepoint': 9,
   'cloudcover': 9,
   'seeing': 4,
   'transparency': 6,
   'lifted_index': 2,
   'rh2m': 12,
   'wind10m': {'direction': 'S', 'speed': 3},
   'temp2m': 10,
   'prec_type': 'rain'},
  {'timepoint': 12,
   'cloudcover': 9,
   'seeing': 4,
   'transparency': 7,
   'lifted_index': 6,
   'rh2m': 13,
   'wind10m': {'direction': 'S', 'speed': 3},
   'temp2m': 9,
   'prec_type': 'rain'},
  {'timepoint': 15,
   'cloudcover': 9,
   'seeing': 4,
   'transparency': 6,
   'lifted_index': 6,
   'rh2m': 13,
   'wind10m': {'direction': 'W', 'speed': 2},
   'temp2m': 8,
   'prec_type': 'rain'},
  {'timepoint': 18,
   'cloudcover': 9,
   'seeing': 5,
   'transparency': 3,
   'lifted_index': 6,
   'rh2m': 12,
   'wind10m': {'direction': 'W', 'speed': 2},
   'temp2m': 7,
   'prec_type': 'rain'},
  {'timepoint': 21,
   'cloudcover': 9,
   'seeing': 5,
   'transparency': 3,
   'lifted_index': 6,
   'rh2m': 11,
   'wind10m': {'direction': 'W', 'speed': 2},
   'temp2m': 6,
   'prec_type': 'none'},
  {'timepoint': 24,
   'cloudcover': 9,
   'seeing': 5,
   'transparency': 4,
   'lifted_index': 6,
   'rh2m': 12,
   'wind10m': {'direction': 'W', 'speed': 2},
   'temp2m': 6,
   'prec_type': 'none'},
  {'timepoint': 27,
   'cloudcover': 9,
   'seeing': 3,
   'transparency': 5,
   'lifted_index': 6,
   'rh2m': 12,
   'wind10m': {'direction': 'W', 'speed': 2},
   'temp2m': 6,
   'prec_type': 'none'},
  {'timepoint': 30,
   'cloudcover': 7,
   'seeing': 3,
   'transparency': 4,
   'lifted_index': 6,
   'rh2m': 11,
   'wind10m': {'direction': 'NW', 'speed': 3},
   'temp2m': 7,
   'prec_type': 'none'},
  {'timepoint': 33,
   'cloudcover': 5,
   'seeing': 3,
   'transparency': 2,
   'lifted_index': 10,
   'rh2m': 7,
   'wind10m': {'direction': 'NW', 'speed': 3},
   'temp2m': 6,
   'prec_type': 'rain'},
  {'timepoint': 36,
   'cloudcover': 3,
   'seeing': 6,
   'transparency': 2,
   'lifted_index': 15,
   'rh2m': 9,
   'wind10m': {'direction': 'W', 'speed': 2},
   'temp2m': 4,
   'prec_type': 'none'},
  {'timepoint': 39,
   'cloudcover': 2,
   'seeing': -9999,
   'transparency': -9999,
   'lifted_index': -9999,
   'rh2m': -9999,
   'wind10m': {'direction': 'SW', 'speed': 2},
   'temp2m': 3,
   'prec_type': 'none'},
  {'timepoint': 42,
   'cloudcover': 2,
   'seeing': 6,
   'transparency': 3,
   'lifted_index': 15,
   'rh2m': 11,
   'wind10m': {'direction': 'SW', 'speed': 2},
   'temp2m': 3,
   'prec_type': 'none'},
  {'timepoint': 45,
   'cloudcover': 7,
   'seeing': 6,
   'transparency': 3,
   'lifted_index': 15,
   'rh2m': 12,
   'wind10m': {'direction': 'S', 'speed': 2},
   'temp2m': 3,
   'prec_type': 'none'},
  {'timepoint': 48,
   'cloudcover': 8,
   'seeing': 6,
   'transparency': 4,
   'lifted_index': 15,
   'rh2m': 12,
   'wind10m': {'direction': 'S', 'speed': 2},
   'temp2m': 3,
   'prec_type': 'none'},
  {'timepoint': 51,
   'cloudcover': 9,
   'seeing': 4,
   'transparency': 4,
   'lifted_index': 15,
   'rh2m': 11,
   'wind10m': {'direction': 'S', 'speed': 3},
   'temp2m': 3,
   'prec_type': 'none'},
  {'timepoint': 54,
   'cloudcover': 8,
   'seeing': 4,
   'transparency': 3,
   'lifted_index': 15,
   'rh2m': 8,
   'wind10m': {'direction': 'S', 'speed': 3},
   'temp2m': 6,
   'prec_type': 'none'},
  {'timepoint': 57,
   'cloudcover': 9,
   'seeing': 4,
   'transparency': 2,
   'lifted_index': 15,
   'rh2m': 8,
   'wind10m': {'direction': 'S', 'speed': 3},
   'temp2m': 6,
   'prec_type': 'none'},
  {'timepoint': 60,
   'cloudcover': 9,
   'seeing': 5,
   'transparency': 3,
   'lifted_index': 15,
   'rh2m': 9,
   'wind10m': {'direction': 'S', 'speed': 3},
   'temp2m': 5,
   'prec_type': 'none'},
  {'timepoint': 63,
   'cloudcover': 9,
   'seeing': 5,
   'transparency': 3,
   'lifted_index': 15,
   'rh2m': 9,
   'wind10m': {'direction': 'S', 'speed': 3},
   'temp2m': 4,
   'prec_type': 'none'},
  {'timepoint': 66,
   'cloudcover': 9,
   'seeing': 5,
   'transparency': 4,
   'lifted_index': 15,
   'rh2m': 11,
   'wind10m': {'direction': 'S', 'speed': 3},
   'temp2m': 4,
   'prec_type': 'none'},
  {'timepoint': 69,
   'cloudcover': 9,
   'seeing': 5,
   'transparency': 3,
   'lifted_index': 15,
   'rh2m': 10,
   'wind10m': {'direction': 'S', 'speed': 3},
   'temp2m': 4,
   'prec_type': 'none'},
  {'timepoint': 72,
   'cloudcover': 9,
   'seeing': 3,
   'transparency': 4,
   'lifted_index': 15,
   'rh2m': 10,
   'wind10m': {'direction': 'S', 'speed': 3},
   'temp2m': 3,
   'prec_type': 'rain'}]}

In [24]:
request

{'product': 'astro',
 'init': '2025112718',
 'dataseries': [{'timepoint': 3,
   'cloudcover': 9,
   'seeing': 5,
   'transparency': 6,
   'lifted_index': 15,
   'rh2m': 13,
   'wind10m': {'direction': 'S', 'speed': 3},
   'temp2m': 6,
   'prec_type': 'none'},
  {'timepoint': 6,
   'cloudcover': 9,
   'seeing': 5,
   'transparency': 8,
   'lifted_index': 15,
   'rh2m': 14,
   'wind10m': {'direction': 'SW', 'speed': 3},
   'temp2m': 6,
   'prec_type': 'none'},
  {'timepoint': 9,
   'cloudcover': 9,
   'seeing': 4,
   'transparency': 8,
   'lifted_index': 15,
   'rh2m': 15,
   'wind10m': {'direction': 'S', 'speed': 3},
   'temp2m': 7,
   'prec_type': 'rain'},
  {'timepoint': 12,
   'cloudcover': 9,
   'seeing': 4,
   'transparency': 8,
   'lifted_index': 15,
   'rh2m': 15,
   'wind10m': {'direction': 'S', 'speed': 2},
   'temp2m': 7,
   'prec_type': 'rain'},
  {'timepoint': 15,
   'cloudcover': 9,
   'seeing': -9999,
   'transparency': -9999,
   'lifted_index': -9999,
   'rh2m': -9999,
   'wind10m': {'direction': 'S', 'speed': 3},
   'temp2m': 8,
   'prec_type': 'none'},
  {'timepoint': 18,
   'cloudcover': 9,
   'seeing': 4,
   'transparency': 8,
   'lifted_index': 10,
   'rh2m': 15,
   'wind10m': {'direction': 'S', 'speed': 3},
   'temp2m': 8,
   'prec_type': 'rain'},
  {'timepoint': 21,
   'cloudcover': 9,
   'seeing': 4,
   'transparency': 8,
   'lifted_index': 6,
   'rh2m': 14,
   'wind10m': {'direction': 'SW', 'speed': 3},
   'temp2m': 9,
   'prec_type': 'rain'},
  {'timepoint': 24,
   'cloudcover': 9,
   'seeing': 5,
   'transparency': 8,
   'lifted_index': 6,
   'rh2m': 15,
   'wind10m': {'direction': 'SW', 'speed': 2},
   'temp2m': 9,
   'prec_type': 'rain'},
  {'timepoint': 27,
   'cloudcover': 1,
   'seeing': 6,
   'transparency': 6,
   'lifted_index': 6,
   'rh2m': 15,
   'wind10m': {'direction': 'SW', 'speed': 2},
   'temp2m': 7,
   'prec_type': 'none'},
  {'timepoint': 30,
   'cloudcover': 4,
   'seeing': 6,
   'transparency': 7,
   'lifted_index': 10,
   'rh2m': 15,
   'wind10m': {'direction': 'SW', 'speed': 2},
   'temp2m': 6,
   'prec_type': 'none'},
  {'timepoint': 33,
   'cloudcover': 9,
   'seeing': 5,
   'transparency': 8,
   'lifted_index': 10,
   'rh2m': 15,
   'wind10m': {'direction': 'S', 'speed': 2},
   'temp2m': 6,
   'prec_type': 'none'},
  {'timepoint': 36,
   'cloudcover': 9,
   'seeing': 5,
   'transparency': 8,
   'lifted_index': 10,
   'rh2m': 15,
   'wind10m': {'direction': 'S', 'speed': 3},
   'temp2m': 6,
   'prec_type': 'none'},
  {'timepoint': 39,
   'cloudcover': 9,
   'seeing': 4,
   'transparency': 8,
   'lifted_index': 10,
   'rh2m': 14,
   'wind10m': {'direction': 'S', 'speed': 3},
   'temp2m': 7,
   'prec_type': 'none'},
  {'timepoint': 42,
   'cloudcover': 9,
   'seeing': 3,
   'transparency': 8,
   'lifted_index': 6,
   'rh2m': 13,
   'wind10m': {'direction': 'S', 'speed': 3},
   'temp2m': 9,
   'prec_type': 'none'},
  {'timepoint': 45,
   'cloudcover': 9,
   'seeing': 4,
   'transparency': 7,
   'lifted_index': 6,
   'rh2m': 13,
   'wind10m': {'direction': 'S', 'speed': 3},
   'temp2m': 9,
   'prec_type': 'rain'},
  {'timepoint': 48,
   'cloudcover': 9,
   'seeing': 4,
   'transparency': 8,
   'lifted_index': 6,
   'rh2m': 13,
   'wind10m': {'direction': 'S', 'speed': 3},
   'temp2m': 9,
   'prec_type': 'rain'},
  {'timepoint': 51,
   'cloudcover': 9,
   'seeing': 4,
   'transparency': 8,
   'lifted_index': 6,
   'rh2m': 14,
   'wind10m': {'direction': 'W', 'speed': 3},
   'temp2m': 9,
   'prec_type': 'rain'},
  {'timepoint': 54,
   'cloudcover': 9,
   'seeing': 4,
   'transparency': 4,
   'lifted_index': 6,
   'rh2m': 11,
   'wind10m': {'direction': 'W', 'speed': 3},
   'temp2m': 7,
   'prec_type': 'rain'},
  {'timepoint': 57,
   'cloudcover': 9,
   'seeing': 5,
   'transparency': 3,
   'lifted_index': 6,
   'rh2m': 11,
   'wind10m': {'direction': 'W', 'speed': 2},
   'temp2m': 6,
   'prec_type': 'none'},
  {'timepoint': 60,
   'cloudcover': 9,
   'seeing': 5,
   'transparency': 5,
   'lifted_index': 6,
   'rh2m': 12,
   'wind10m': {'direction': 'W', 'speed': 2},
   'temp2m': 5,
   'prec_type': 'none'},
  {'timepoint': 63,
   'cloudcover': 8,
   'seeing': 3,
   'transparency': 4,
   'lifted_index': 6,
   'rh2m': 11,
   'wind10m': {'direction': 'NW', 'speed': 2},
   'temp2m': 5,
   'prec_type': 'none'},
  {'timepoint': 66,
   'cloudcover': 7,
   'seeing': 3,
   'transparency': 3,
   'lifted_index': 10,
   'rh2m': 8,
   'wind10m': {'direction': 'W', 'speed': 3},
   'temp2m': 7,
   'prec_type': 'none'},
  {'timepoint': 69,
   'cloudcover': 2,
   'seeing': 4,
   'transparency': 2,
   'lifted_index': 10,
   'rh2m': 7,
   'wind10m': {'direction': 'W', 'speed': 2},
   'temp2m': 6,
   'prec_type': 'none'},
  {'timepoint': 72,
   'cloudcover': 2,
   'seeing': 6,
   'transparency': 2,
   'lifted_index': 15,
   'rh2m': 9,
   'wind10m': {'direction': 'W', 'speed': 2},
   'temp2m': 4,
   'prec_type': 'none'}]}

In [5]:
df = pd.DataFrame(request)

In [8]:
df.melt(id_vars=["dataseries"], var_name="attribute", value_name="value")

                                           dataseries attribute       value
0   {'timepoint': 3, 'cloudcover': 9, 'seeing': 3,...   product       astro
1   {'timepoint': 6, 'cloudcover': 9, 'seeing': 4,...   product       astro
2   {'timepoint': 9, 'cloudcover': 9, 'seeing': 5,...   product       astro
3   {'timepoint': 12, 'cloudcover': 9, 'seeing': 4...   product       astro
4   {'timepoint': 15, 'cloudcover': 9, 'seeing': 4...   product       astro
5   {'timepoint': 18, 'cloudcover': 9, 'seeing': 5...   product       astro
6   {'timepoint': 21, 'cloudcover': 9, 'seeing': 4...   product       astro
7   {'timepoint': 24, 'cloudcover': 9, 'seeing': 4...   product       astro
8   {'timepoint': 27, 'cloudcover': 9, 'seeing': 4...   product       astro
9   {'timepoint': 30, 'cloudcover': 9, 'seeing': 4...   product       astro
10  {'timepoint': 33, 'cloudcover': 3, 'seeing': 6...   product       astro
11  {'timepoint': 36, 'cloudcover': 4, 'seeing': 6...   product       astro
12  {'timepoint': 39, 'cloudcover': 9, 'seeing': 6...   product       astro
13  {'timepoint': 42, 'cloudcover': 9, 'seeing': 5...   product       astro
14  {'timepoint': 45, 'cloudcover': 9, 'seeing': 4...   product       astro
15  {'timepoint': 48, 'cloudcover': 9, 'seeing': 3...   product       astro
16  {'timepoint': 51, 'cloudcover': 9, 'seeing': 4...   product       astro
17  {'timepoint': 54, 'cloudcover': 9, 'seeing': 4...   product       astro
18  {'timepoint': 57, 'cloudcover': 9, 'seeing': 4...   product       astro
19  {'timepoint': 60, 'cloudcover': 9, 'seeing': 3...   product       astro
20  {'timepoint': 63, 'cloudcover': 8, 'seeing': 5...   product       astro
21  {'timepoint': 66, 'cloudcover': 8, 'seeing': 4...   product       astro
22  {'timepoint': 69, 'cloudcover': 9, 'seeing': 3...   product       astro
23  {'timepoint': 72, 'cloudcover': 8, 'seeing': 3...   product       astro
24  {'timepoint': 3, 'cloudcover': 9, 'seeing': 3,...      init  2025112712
25  {'timepoint': 6, 'cloudcover': 9, 'seeing': 4,...      init  2025112712
26  {'timepoint': 9, 'cloudcover': 9, 'seeing': 5,...      init  2025112712
27  {'timepoint': 12, 'cloudcover': 9, 'seeing': 4...      init  2025112712
28  {'timepoint': 15, 'cloudcover': 9, 'seeing': 4...      init  2025112712
29  {'timepoint': 18, 'cloudcover': 9, 'seeing': 5...      init  2025112712
30  {'timepoint': 21, 'cloudcover': 9, 'seeing': 4...      init  2025112712
31  {'timepoint': 24, 'cloudcover': 9, 'seeing': 4...      init  2025112712
32  {'timepoint': 27, 'cloudcover': 9, 'seeing': 4...      init  2025112712
33  {'timepoint': 30, 'cloudcover': 9, 'seeing': 4...      init  2025112712
34  {'timepoint': 33, 'cloudcover': 3, 'seeing': 6...      init  2025112712
35  {'timepoint': 36, 'cloudcover': 4, 'seeing': 6...      init  2025112712
36  {'timepoint': 39, 'cloudcover': 9, 'seeing': 6...      init  2025112712
37  {'timepoint': 42, 'cloudcover': 9, 'seeing': 5...      init  2025112712
38  {'timepoint': 45, 'cloudcover': 9, 'seeing': 4...      init  2025112712
39  {'timepoint': 48, 'cloudcover': 9, 'seeing': 3...      init  2025112712
40  {'timepoint': 51, 'cloudcover': 9, 'seeing': 4...      init  2025112712
41  {'timepoint': 54, 'cloudcover': 9, 'seeing': 4...      init  2025112712
42  {'timepoint': 57, 'cloudcover': 9, 'seeing': 4...      init  2025112712
43  {'timepoint': 60, 'cloudcover': 9, 'seeing': 3...      init  2025112712
44  {'timepoint': 63, 'cloudcover': 8, 'seeing': 5...      init  2025112712
45  {'timepoint': 66, 'cloudcover': 8, 'seeing': 4...      init  2025112712
46  {'timepoint': 69, 'cloudcover': 9, 'seeing': 3...      init  2025112712
47  {'timepoint': 72, 'cloudcover': 8, 'seeing': 3...      init  2025112712

In [17]:
df = pd.json_normalize(
    request,
    record_path='dataseries',
    meta=['product', 'init']
)

In [18]:
df

,timepoint,cloudcover,seeing,transparency,lifted_index,rh2m,temp2m,prec_type,wind10m.direction,wind10m.speed,product,init
0,3,9,3,4,15,11,6,none,S,3,astro,2025112712
1,6,9,4,4,15,11,6,none,S,3,astro,2025112712
2,9,9,5,6,15,12,6,none,S,3,astro,2025112712
3,12,9,4,8,15,13,7,none,SW,3,astro,2025112712
4,15,9,4,8,15,15,7,rain,S,2,astro,2025112712
5,18,9,5,8,15,15,8,rain,S,2,astro,2025112712
6,21,9,4,8,10,15,8,rain,S,3,astro,2025112712
7,24,9,4,8,6,15,9,rain,SW,3,astro,2025112712
8,27,9,4,8,6,14,9,rain,SW,3,astro,2025112712
9,30,9,4,8,6,15,9,rain,SW,2,astro,2025112712
10,33,3,6,6,6,15,7,none,SW,2,astro,2025112712
11,36,4,6,5,10,14,6,none,SW,2,astro,2025112712
12,39,9,6,8,10,15,6,none,S,2,astro,2025112712
13,42,9,5,8,10,15,6,none,S,2,astro,2025112712
14,45,9,4,8,10,14,7,none,S,3,astro,2025112712
15,48,9,3,6,6,12,9,none,S,3,astro,2025112712
16,51,9,4,5,6,12,10,none,S,3,astro,2025112712
17,54,9,4,8,6,14,9,rain,S,3,astro,2025112712
18,57,9,4,8,2,13,9,rain,S,3,astro,2025112712
19,60,9,3,4,6,11,8,rain,W,3,astro,2025112712
20,63,8,5,4,10,11,6,none,W,3,astro,2025112712
21,66,8,4,5,10,12,5,none,W,2,astro,2025112712
22,69,9,3,5,6,11,5,rain,W,3,astro,2025112712
23,72,8,3,2,10,6,7,rain,NW,3,astro,2025112712

In [11]:
request

{'product': 'astro',
 'init': '2025112712',
 'dataseries': [{'timepoint': 3,
   'cloudcover': 9,
   'seeing': 3,
   'transparency': 4,
   'lifted_index': 15,
   'rh2m': 11,
   'wind10m': {'direction': 'S', 'speed': 3},
   'temp2m': 6,
   'prec_type': 'none'},
  {'timepoint': 6,
   'cloudcover': 9,
   'seeing': 4,
   'transparency': 4,
   'lifted_index': 15,
   'rh2m': 11,
   'wind10m': {'direction': 'S', 'speed': 3},
   'temp2m': 6,
   'prec_type': 'none'},
  {'timepoint': 9,
   'cloudcover': 9,
   'seeing': 5,
   'transparency': 6,
   'lifted_index': 15,
   'rh2m': 12,
   'wind10m': {'direction': 'S', 'speed': 3},
   'temp2m': 6,
   'prec_type': 'none'},
  {'timepoint': 12,
   'cloudcover': 9,
   'seeing': 4,
   'transparency': 8,
   'lifted_index': 15,
   'rh2m': 13,
   'wind10m': {'direction': 'SW', 'speed': 3},
   'temp2m': 7,
   'prec_type': 'none'},
  {'timepoint': 15,
   'cloudcover': 9,
   'seeing': 4,
   'transparency': 8,
   'lifted_index': 15,
   'rh2m': 15,
   'wind10m': {'direction': 'S', 'speed': 2},
   'temp2m': 7,
   'prec_type': 'rain'},
  {'timepoint': 18,
   'cloudcover': 9,
   'seeing': 5,
   'transparency': 8,
   'lifted_index': 15,
   'rh2m': 15,
   'wind10m': {'direction': 'S', 'speed': 2},
   'temp2m': 8,
   'prec_type': 'rain'},
  {'timepoint': 21,
   'cloudcover': 9,
   'seeing': 4,
   'transparency': 8,
   'lifted_index': 10,
   'rh2m': 15,
   'wind10m': {'direction': 'S', 'speed': 3},
   'temp2m': 8,
   'prec_type': 'rain'},
  {'timepoint': 24,
   'cloudcover': 9,
   'seeing': 4,
   'transparency': 8,
   'lifted_index': 6,
   'rh2m': 15,
   'wind10m': {'direction': 'SW', 'speed': 3},
   'temp2m': 9,
   'prec_type': 'rain'},
  {'timepoint': 27,
   'cloudcover': 9,
   'seeing': 4,
   'transparency': 8,
   'lifted_index': 6,
   'rh2m': 14,
   'wind10m': {'direction': 'SW', 'speed': 3},
   'temp2m': 9,
   'prec_type': 'rain'},
  {'timepoint': 30,
   'cloudcover': 9,
   'seeing': 4,
   'transparency': 8,
   'lifted_index': 6,
   'rh2m': 15,
   'wind10m': {'direction': 'SW', 'speed': 2},
   'temp2m': 9,
   'prec_type': 'rain'},
  {'timepoint': 33,
   'cloudcover': 3,
   'seeing': 6,
   'transparency': 6,
   'lifted_index': 6,
   'rh2m': 15,
   'wind10m': {'direction': 'SW', 'speed': 2},
   'temp2m': 7,
   'prec_type': 'none'},
  {'timepoint': 36,
   'cloudcover': 4,
   'seeing': 6,
   'transparency': 5,
   'lifted_index': 10,
   'rh2m': 14,
   'wind10m': {'direction': 'SW', 'speed': 2},
   'temp2m': 6,
   'prec_type': 'none'},
  {'timepoint': 39,
   'cloudcover': 9,
   'seeing': 6,
   'transparency': 8,
   'lifted_index': 10,
   'rh2m': 15,
   'wind10m': {'direction': 'S', 'speed': 2},
   'temp2m': 6,
   'prec_type': 'none'},
  {'timepoint': 42,
   'cloudcover': 9,
   'seeing': 5,
   'transparency': 8,
   'lifted_index': 10,
   'rh2m': 15,
   'wind10m': {'direction': 'S', 'speed': 2},
   'temp2m': 6,
   'prec_type': 'none'},
  {'timepoint': 45,
   'cloudcover': 9,
   'seeing': 4,
   'transparency': 8,
   'lifted_index': 10,
   'rh2m': 14,
   'wind10m': {'direction': 'S', 'speed': 3},
   'temp2m': 7,
   'prec_type': 'none'},
  {'timepoint': 48,
   'cloudcover': 9,
   'seeing': 3,
   'transparency': 6,
   'lifted_index': 6,
   'rh2m': 12,
   'wind10m': {'direction': 'S', 'speed': 3},
   'temp2m': 9,
   'prec_type': 'none'},
  {'timepoint': 51,
   'cloudcover': 9,
   'seeing': 4,
   'transparency': 5,
   'lifted_index': 6,
   'rh2m': 12,
   'wind10m': {'direction': 'S', 'speed': 3},
   'temp2m': 10,
   'prec_type': 'none'},
  {'timepoint': 54,
   'cloudcover': 9,
   'seeing': 4,
   'transparency': 8,
   'lifted_index': 6,
   'rh2m': 14,
   'wind10m': {'direction': 'S', 'speed': 3},
   'temp2m': 9,
   'prec_type': 'rain'},
  {'timepoint': 57,
   'cloudcover': 9,
   'seeing': 4,
   'transparency': 8,
   'lifted_index': 2,
   'rh2m': 13,
   'wind10m': {'direction': 'S', 'speed': 3},
   'temp2m': 9,
   'prec_type': 'rain'},
  {'timepoint': 60,
   'cloudcover': 9,
   'seeing': 3,
   'transparency': 4,
   'lifted_index': 6,
   'rh2m': 11,
   'wind10m': {'direction': 'W', 'speed': 3},
   'temp2m': 8,
   'prec_type': 'rain'},
  {'timepoint': 63,
   'cloudcover': 8,
   'seeing': 5,
   'transparency': 4,
   'lifted_index': 10,
   'rh2m': 11,
   'wind10m': {'direction': 'W', 'speed': 3},
   'temp2m': 6,
   'prec_type': 'none'},
  {'timepoint': 66,
   'cloudcover': 8,
   'seeing': 4,
   'transparency': 5,
   'lifted_index': 10,
   'rh2m': 12,
   'wind10m': {'direction': 'W', 'speed': 2},
   'temp2m': 5,
   'prec_type': 'none'},
  {'timepoint': 69,
   'cloudcover': 9,
   'seeing': 3,
   'transparency': 5,
   'lifted_index': 6,
   'rh2m': 11,
   'wind10m': {'direction': 'W', 'speed': 3},
   'temp2m': 5,
   'prec_type': 'rain'},
  {'timepoint': 72,
   'cloudcover': 8,
   'seeing': 3,
   'transparency': 2,
   'lifted_index': 10,
   'rh2m': 6,
   'wind10m': {'direction': 'NW', 'speed': 3},
   'temp2m': 7,
   'prec_type': 'rain'}]}